dist: xenial
language: csharp

services:
  - docker
script: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t asprakendus .
  - docker images
  - docker tag asprakendus $DOCKER_USERNAME/asprakendus
  - docker push $DOCKER_USERNAME/asprakendus
