dist: xenial
language: csharp

services:
  - docker
script: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t aspnet .
  - docker images
  - docker tag aspnet $DOCKER_USERNAME/aspnet
  - docker push $DOCKER_USERNAME/aspnet
